Marketing/Controllers/AboutController.cs
using Marketing.DataAccess;
using Marketing.DataAccess.Interface;
using Marketing.DataAccess.Repositories;
using Marketing.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;


namespace Marketing.Controllers
{
    public class AboutController : Controller
    {
        private IContactUsManagementRepository contactRepository;
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ContactUs()
        {
            return View();
        }
        [HttpPost]
        public ActionResult ContactUs(ContactUsModel model)
        {
            var msg = string.Empty;
            if (ModelState.IsValid)
            {
                using (contactRepository = new ContactUsManagementRepository())
                {
                    var contact = new Marketing.Data.ContactUs();
                    contact.CountryId = model.CountryId;
                    contact.FirstName = model.FirstName;
                    contact.LastName = model.LastName;
                    contact.Phone = model.Phone;
                    contact.Email = model.Email;
                    contact.Comments = model.Comments;
                    contact.WebSiteId = 1;
                    msg = contactRepository.Submit(contact);
                }
            }
            else
            {
                ModelState.AddModelError("", "Contact Us data is incorrect!");
            }
            ViewBag.Message = msg;
            return View(model);
        }
    }
}

Marketing/Controllers/CouponController.cs
using Marketing.Business.Interface;
using Marketing.Business.Services;
using Marketing.Common;
using Marketing.Data;
using Marketing.DataAccess;
using Marketing.DataAccess.Interface;
using Marketing.DataAccess.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Marketing.Controllers
{
    public class CouponController : BaseController
    {
        public IModelManagementService _mapperService { get; set; }
        public ICouponRepository couponRepository { get; set; }
        public IStoreRepository storeRepository { get; set; }
        public ICategoryRepository categoryRepository { get; set; }
        public IImageRepository imageRepository { get; set; }
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Details(int Id)
        {
            var model = new Marketing.Business.Models.Coupon();
            _mapperService = new ModelManagementService();
            using (couponRepository = new CouponRepository()) 
            {
               if (Id > 0)
                {
                    model = _mapperService.MapCouponToModel(couponRepository.FindById(Id));
                }
            }
            return View(model);
        }
        public ActionResult Edit(int Id)
        {
            var model = new Marketing.Business.Models.Coupon();
            _mapperService = new ModelManagementService();
            using (storeRepository = new StoreRepository())
            {
                using (categoryRepository = new CategoryRepository())
                {
                    var categories = categoryRepository.All().ToList();
                    var stores = storeRepository.All().ToList();
                    foreach (var item in categories)
                    {
                        model.Categories.Add(new SelectListItem()
                        {
                            Text = item.Name,
                            Value = item.Id.ToString()
                        });

                    }
                    foreach (var item in stores)
                    {
                        model.Stores.Add(new SelectListItem()
                        {
                            Text = item.Name,
                            Value = item.Id.ToString()
                        });

                    }
                    if (Id > 0)
                    {
                        // model = _mapperService.MapCouponToModel(couponRepository.FindById(Id));
                         var coupon = new Data.Coupon();
                         coupon.Id = model.Id;
                         coupon.Name = model.Name;
                         coupon.Published = model.Published;
                         coupon.ShowOnHomePage = model.ShowOnHomePage;
                         coupon.IsFeatured = model.IsFeatured;
                         coupon.IncludeInTopMenu = model.IncludeInTopMenu;
                         coupon.FullDescription = model.FullDescription;
                         coupon.CategoryId = model.CategoryId;
                         coupon.StoreId = model.StoreId;
                         coupon.Deleted = model.Deleted;
                         coupon.IsActive = model.IsActive;
                         coupon.Created = DateTimeHelper.Now();
                         coupon.CreatedBy = Session["UName"].ToString();
                         coupon.Modified = DateTimeHelper.Now();
                         coupon.ModifiedBy = Session["UName"].ToString();
                        

                       
                    }
                        }
            }

            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Marketing.Business.Models.Coupon model)
        {
            if (ModelState.IsValid)
            {
                using (couponRepository = new CouponRepository())
                using (imageRepository = new ImageRepository())
                {
                    var image = new Image()
                    {
                        Name = model.ImagePath,
                        Created = DateTimeHelper.Now(),
                        CreatedBy = Session["UName"].ToString(),
                        IsActive = true,
                        Modified = DateTimeHelper.Now(),
                        ModifiedBy = Session["UName"].ToString()
                    };
                    image = imageRepository.Insert(image);

                    var coupon = new Data.Coupon();
                    coupon.Id = model.Id;
                    coupon.Name = model.Name;
                    coupon.Published = model.Published;
                    coupon.ShowOnHomePage = model.ShowOnHomePage;
                    coupon.IsFeatured = model.IsFeatured;
                    coupon.IncludeInTopMenu = model.IncludeInTopMenu;
                    coupon.FullDescription = model.FullDescription;
                    coupon.CategoryId = model.CategoryId;
                    coupon.StoreId = model.StoreId;
                    coupon.Deleted = model.Deleted;
                    coupon.IsActive = model.IsActive;
                    coupon.Created = DateTimeHelper.Now();
                    coupon.CreatedBy = Session["UName"].ToString();
                    coupon.Modified = DateTimeHelper.Now();
                    coupon.ModifiedBy = Session["UName"].ToString();
                    coupon.ImageId = image.Id;
                    if (model.Id > 0)
                    {

                        using (couponRepository = new CouponRepository())
                        using (imageRepository = new ImageRepository())
                        {
                            var imageUpdate = new Image()
                            {
                                Name = model.ImagePath,
                                Created = DateTimeHelper.Now(),
                                CreatedBy = Session["UName"].ToString(),
                                IsActive = true,
                                Modified = DateTimeHelper.Now(),
                                ModifiedBy = Session["UName"].ToString()
                            };
                            imageUpdate = imageRepository.Update(imageUpdate);
                            var couponUpdate = new Data.Coupon();
                            coupon.Id = model.Id;
                            coupon.Name = model.Name;
                            coupon.Published = model.Published;
                            coupon.ShowOnHomePage = model.ShowOnHomePage;
                            coupon.IsFeatured = model.IsFeatured;
                            coupon.IncludeInTopMenu = model.IncludeInTopMenu;
                            coupon.FullDescription = model.FullDescription;
                            coupon.CategoryId = model.CategoryId;
                            coupon.StoreId = model.StoreId;
                            coupon.Deleted = model.Deleted;
                            coupon.IsActive = model.IsActive;
                            coupon.Created = DateTimeHelper.Now();
                            coupon.CreatedBy = Session["UName"].ToString();
                            coupon.Modified = DateTimeHelper.Now();
                            coupon.ModifiedBy = Session["UName"].ToString();

                            couponRepository.Update(coupon);

                        }

                    }
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Login data is incorrect!");
                return View(model);                    
            }
        }
        public ActionResult List()
        {
            if (Session["IsAdmin"] == null)
                return RedirectToAction("Login", "User");
            _mapperService = new ModelManagementService();
            var model = new List<Marketing.Business.Models.Coupon>();
            using (couponRepository = new CouponRepository())
            {
                model = _mapperService.MapCouponsToModel(couponRepository.All()).ToList();
            }
            return View(model);
        }
    }
}

Marketing/Controllers/StoreController.cs
using Marketing.Business.Interface;
using Marketing.Business.Models;
using Marketing.Business.Services;
using Marketing.Common;
using Marketing.Data;
using Marketing.DataAccess;
using Marketing.DataAccess.Interface;
using Marketing.DataAccess.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace Marketing.Controllers
{
    public class StoreController : BaseController
    {
        //private IStoreRepository storeRepository;
        public IModelManagementService _mapperService { get; set; }
        public IStoreRepository storeRepository { get; set; }
        public IImageRepository imageRepository { get; set; }
        
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Details(int Id)
        {
            var model = new Marketing.Business.Models.Store();
            _mapperService = new ModelManagementService();
            using (storeRepository = new StoreRepository())
            {
                if (Id > 0)
                {
                    model = _mapperService.MapStoreToModel(storeRepository.FindById(Id));
                }
            }
            return View(model);
        }


        public ActionResult Edit(int Id)
        {
            var model = new Marketing.Business.Models.Store();
            if (Id > 0)
            {
                _mapperService = new ModelManagementService();
                using (storeRepository = new StoreRepository())
                {
                    model = _mapperService.MapStoreToModel(storeRepository.FindById(Id));
                }
            }
            return View(model);
        }
        [HttpPost]
        public ActionResult Edit(Marketing.Business.Models.Store model)
        {
            if (ModelState.IsValid)
            {
                using (storeRepository = new StoreRepository())
                using (imageRepository = new ImageRepository())
                {
                    var image = new Image()
                    {
                        Name = model.ImagePath,
                        Created = DateTimeHelper.Now(),
                        CreatedBy = Session["UName"].ToString(),
                        IsActive = true,
                        Modified = DateTimeHelper.Now(),
                        ModifiedBy = Session["UName"].ToString()
                    };
                    image = imageRepository.Insert(image);
                    var store = new Data.Store();
                    store.Name = model.Name;
                    store.Published = model.Published;
                    store.ShowOnHomePage = model.ShowOnHomePage;
                    store.CompanyId = 0;
                    store.CompanyName = model.CompanyName;
                    store.CompanyPhoneNo = model.CompanyPhoneNo;
                    store.IsNew = model.IsNew;
                    store.IsPopular = model.IsPopular;
                    store.IsFeatured = model.IsFeatured;
                    store.IncludeInTopMenu = model.IncludeInTopMenu;
                    store.Deleted = model.Deleted;
                    store.WebSiteId = WebSite.Id;
                    store.IsActive = model.IsActive;
                    store.Created = DateTimeHelper.Now();
                    store.CreatedBy = Session["UName"].ToString();
                    store.Modified = DateTimeHelper.Now();
                    store.ModifiedBy = Session["UName"].ToString();
                    store.ImageId = image.Id;
                    if (model.Id > 0)
                    {
                        store = storeRepository.FindById(model.Id);
                        storeRepository.Update(store);
                    }
                    else
                    {
                        storeRepository.Insert(store);
                    }
                }
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ModelState.AddModelError("", "Store data is incorrect!");
                return View(model);
            }
        }
    }
}

Marketing/Views/Shared/_AdminMenu.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
@{
    var model = ViewBag.HeaderMenu != null ? ViewBag.HeaderMenu : new Marketing.Models.HeaderMenu();
}
<nav class="navbar navbar-inverse">
    @if (Session["IsAdmin"] != null)
    {
        <div style=" text-align: center;padding: 10px 10px 10px 10px;background-color: darkgray;"><a href="/Administrator" style="color: white; font-size: 17px;text-decoration:none">Administrator</a></div>
    }
    <div class="navbar-header">
        <div class="container">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="~/img/logo.jpg" alt="logo" class="img-responsive" style="max-width: 191px;margin-top: -10px;" /></a>
            <div class="collapse navbar-collapse js-navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown mega-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Admin <span class="caret"></span></a>
                        <ul class="dropdown-menu mega-dropdown-menu">
                            <li class="col-sm-10">
                                <a href="#">@Html.ActionLink("Search Users", "List", "User")</a>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown mega-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Stores <span class="caret"></span></a>
                        <ul class="dropdown-menu mega-dropdown-menu">
                            <li class="col-sm-10">
                                <ul>
                                    <li><a href="#">@Html.ActionLink("Add New Store", "Edit", "Store", new { Id = 0 }, null)</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">@Html.ActionLink("Search Stores", "List", "Store")</a></li>
                                    <li class="divider"></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown mega-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
                        <ul class="dropdown-menu mega-dropdown-menu">
                            <li class="col-sm-10">
                                <ul>
                                    <li><a href="#">@Html.ActionLink("Add New Category", "Edit", "Category", new { Id = 0, type = "Category" }, null)</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">@Html.ActionLink("Search Categories", "List", "Category", new { type = "Category" }, null)</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">@Html.ActionLink("Add New Sub-Category", "Edit", "Category", new { Id = 0, type = "SubCategory" }, null)</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">@Html.ActionLink("Search Sub-Category", "List", "Category", new { type = "SubCategory" }, null)</a></li>
                                    <li class="divider"></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown mega-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Coupons<span class="caret"></span></a>
                        <ul class="dropdown-menu mega-dropdown-menu">
                            <li class="col-sm-10">
                                <ul>
                                    <li><a href="#">@Html.ActionLink("Add New Coupon", "Edit", "Coupon", new { Id = 0 }, null)</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">@Html.ActionLink("Search Coupons", "List", "Coupon")</a></li>
                                    <li class="divider"></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown mega-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Networks<span class="caret"></span></a>
                        <ul class="dropdown-menu mega-dropdown-menu">
                            <li class="col-sm-10">
                                <ul>
                                    <li><a href="#">@Html.ActionLink("Add New Network", "Edit", "Network", new { Id = 0 }, null)</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">@Html.ActionLink("Search Networks", "List", "Network")</a></li>
                                    <li class="divider"></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    @if (Session["UName"] != null)
                    {
                        <strong>Hi! @Html.Encode(Session["UName"])</strong>
                        @Html.ActionLink("Sign Out", "Logout", "User")

                    }
                    else
                    {
                        @Html.ActionLink("Register", "Register", "User", null, new { style = "color: #777 text-shadow: 0 1px 0 rgba(255, 255, 255, .25);" })
                        <span> | </span>
                        @Html.ActionLink("Sign In", "Login", "User", null, new { style = "color: #777; text-shadow: 0 1px 0 rgba(255, 255, 255, .25);" })
                    }
                    <li><a href="#">My cart (0) items</a></li>
                </ul>
            </div>
        </div>
    </div><!-- /.nav-collapse -->
</nav>

Marketing/Views/Shared/_Coupons.cshtml
@model List<Marketing.Business.Models.Coupon>
<div class="col-md-12">
    @foreach (var item in Model)
    {
        <div class="span4">
            <div class="col-md-4">
                <a href="@item.Name">
                    <p id="offer-1">@item.Name</p>
                    <a href="/Coupon/Details/@item.Id">
                        <img src="@item.ImagePath"
                             alt="@item.Name" class="img-responsive" style="max-width: 100%;height: 300px;" />
                    </a>
                </a>
            </div>
        </div>
    }
</div>

Marketing/Views/Shared/_Menu.cshtml
<!DOCTYPE HTML PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
@{
    var model = ViewBag.HeaderMenu != null ? ViewBag.HeaderMenu : new Marketing.Models.HeaderMenu();
}
<nav class="navbar navbar-inverse">
    @if (Session["IsAdmin"] != null)
    {
        <div style=" text-align: center;padding: 10px 10px 10px 10px;background-color: darkgray;"><a href="/Administrator" style="color: white; font-size: 17px;text-decoration:none">Administrator</a></div>
    }
    <div class="navbar-header">
        <div class="container">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".js-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/"><img src="~/img/logo.jpg" alt="logo" class="img-responsive" style="max-width: 191px;margin-top: -10px;" /></a>


            <div class="collapse navbar-collapse js-navbar-collapse">
                <ul class="nav navbar-nav">
                    <li class="dropdown mega-dropdown">
                        <a href="" class="dropdown-toggle">Home</a>

                    </li>

                    <li class="dropdown mega-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Categories <span class="caret"></span></a>
                        <ul class="dropdown-menu mega-dropdown-menu">
                            <li class="col-sm-3">
                                <ul>
                                    @foreach (var item in model.Categories)
                                    {
                                        <li class="dropdown-header">@Html.ActionLink((string)item.Name, "Details", "Category", new { Id = @item.Id }, new { type = "Category" })</li>
                                        foreach (var subCategory in item.SubCategories)
                                        {
                                            <li><a href="#">@subCategory.Name</a></li>
                                        }
                                        <li class="divider"></li>
                                    }
                                    @if (Session["IsAdmin"] != null)
                                    {
                                        <li><a href="#">@Html.ActionLink("Add New Category", "Edit", "Category", new { Id = 0, type = "Category" }, new { type = "Category" })</a></li>
                                        <li class="divider"></li>
                                        <li><a href="#">@Html.ActionLink("Add New Sub Category", "Edit", "Category", new { Id = 0, type = "SubCategory" }, new { type = "SubCategory" })</a></li>
                                        <li class="divider"></li>
                                    }
                                    <li><a href="#">Four Columns Grid</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Fonts</li>
                                    <li><a href="#">Glyphicon</a></li>
                                    <li><a href="#">Google Fonts</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-3">
                                <ul>
                                    <li class="dropdown-header">Plus</li>
                                    <li class="divider"></li>
                                    <li><a href="#">Navbar Inverse</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Pull Right Elements</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Coloured Headers</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Primary Buttons & Default</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-3">
                                <ul>
                                    <li class="dropdown-header">Much more</li>
                                    <li><a href="#">Easy to Customize</a></li>
                                    <li><a href="#">Calls to action</a></li>
                                    <li><a href="#">Custom Fonts</a></li>
                                    <li><a href="#">Slide down on Hover</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-3">
                                <ul>

                                    <li><a href="#">@Html.ActionLink("View All Categories", "Categories", "Home")</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="dropdown mega-dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Stores <span class="caret"></span></a>
                        <ul class="dropdown-menu mega-dropdown-menu">
                            <li class="col-sm-3">
                                <ul>
                                    @foreach (var item in model.Stores)
                                    {
                                        <li class="dropdown-header">@Html.ActionLink((string)item.Name, "Details", "Store", new { Id = item.Id }, null)</li>
                                        <li class="divider"></li>
                                    }
                                    @if (Session["IsAdmin"] != null)
                                    {
                                        <li><a href="#">@Html.ActionLink("Add New Store", "Edit", "Store")</a></li>
                                        <li class="divider"></li>

                                    }
                                    <li><a href="#">Four Columns Grid</a></li>
                                    <li class="divider"></li>
                                    <li class="dropdown-header">Fonts</li>
                                    <li><a href="#">Glyphicon</a></li>
                                    <li><a href="#">Google Fonts</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-3">
                                <ul>
                                    <li class="dropdown-header">Plus</li>
                                    <li class="divider"></li>
                                    <li><a href="#">Navbar Inverse</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Pull Right Elements</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Coloured Headers</a></li>
                                    <li class="divider"></li>
                                    <li><a href="#">Primary Buttons & Default</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-3">
                                <ul>
                                    <li class="dropdown-header">Much more</li>
                                    <li><a href="#">Easy to Customize</a></li>
                                    <li><a href="#">Calls to action</a></li>
                                    <li><a href="#">Custom Fonts</a></li>
                                    <li><a href="#">Slide down on Hover</a></li>
                                </ul>
                            </li>
                            <li class="col-sm-3">
                                <ul>

                                    <li><a href="#">@Html.ActionLink("View All Stores", "Stores", "Home")</a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>

                    <li class="dropdown mega-dropdown">
                        <a href="#" class="dropdown-toggle">Coupon Deals </a>

                        @if (Session["IsAdmin"] != null)
                        {
                            <ul class="dropdown-menu mega-dropdown-menu">
                                <li class="col-sm-3">
                                    <ul>
                                        <li class="dropdown-header">@Html.ActionLink("Add New Coupon", "Edit", "Coupon", new { Id = 0, type = "Coupon" }, null)</li>
                                        <li class="divider"></li>
                                    </ul>
                                </li>
                            </ul>
                        }

                    </li>
                </ul>


                <ul class="nav navbar-nav navbar-right">
                    @*<li class="dropdown">
                        <a href="#" class="dropdown-toggle" role="button" aria-expanded="false">My account</a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>*@
                    @if (Session["UName"] != null)
                    {
                        <strong>Hi! @Html.Encode(Session["UName"])</strong>
                        @Html.ActionLink("Sign Out", "Logout", "User")

                    }
                    else
                    {
                        @Html.ActionLink("Register", "Register", "User", null, new { style = "color: #777 text-shadow: 0 1px 0 rgba(255, 255, 255, .25);" })
                        <span> | </span>
                        @Html.ActionLink("Sign In", "Login", "User", null, new { style = "color: #777; text-shadow: 0 1px 0 rgba(255, 255, 255, .25);" })
                    }
                    <li><a href="#">My cart (0) items</a></li>
                </ul>
            </div>
        </div>
    </div><!-- /.nav-collapse -->
</nav>